# Generated by Django 4.2.3 on 2024-12-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_fornecedor_cep_alter_fornecedor_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categories',
            field=models.ManyToManyField(to='produtos.categoria'),
        ),
    ]
