# Generated by Django 4.2.3 on 2024-12-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produto_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categories',
            field=models.ManyToManyField(to='produtos.categoria'),
        ),
    ]
